# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='blogposttag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='blogposttag',
            name='tag',
        ),
        migrations.DeleteModel(
            name='BlogIndexPage',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='BlogPostTag',
        ),
    ]
