# Generated by Django 2.0.3 on 2018-03-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='abbreviation',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
