# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='periodicals/')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periodicals.Issue')),
            ],
        ),
    ]
