# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0002_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='issue',
        ),
    ]
