# Generated by Django 2.0.3 on 2018-03-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0003_alter_field_slug_on_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='edition',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
