# Generated by Django 2.0.3 on 2018-03-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0004_issue_edition'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['publication', 'issue_date', 'edition']},
        ),
    ]
