# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0005_remove_issue_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['page', 'aid']},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['publication', 'issue_date']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['issue', 'number']},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['abbreviation']},
        ),
    ]
