# Generated by Django 2.0.3 on 2018-03-29 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0005_issuecomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='periodicals.IssueComponent'),
        ),
    ]
