# Generated by Django 2.0.3 on 2018-03-31 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0006_issue_issuecomponent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['publication', 'issue_date', 'edition_number']},
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='edition',
            new_name='edition_number',
        ),
    ]
