# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0006_meta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='pdf',
            field=models.FileField(default='', upload_to='periodicals/'),
            preserve_default=False,
        ),
    ]
