# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('periodicals', '0008_remove_page_from_article'), ('periodicals', '0009_article_page_m2m'), ('periodicals', '0010_rename_page_article_pages'), ('periodicals', '0011_article_issue'), ('periodicals', '0012_remove_article_issue'), ('periodicals', '0013_remove_article_pages'), ('periodicals', '0014_article_page'), ('periodicals', '0015_article_continuation_fields'), ('periodicals', '0016_article_issue'), ('periodicals', '0017_alter_field_page_on_article')]

    dependencies = [
        ('periodicals', '0007_page_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.RemoveField(
            model_name='article',
            name='page',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['page', 'aid']},
        ),
        migrations.AddField(
            model_name='article',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='periodicals.Page'),
        ),
        migrations.AddField(
            model_name='article',
            name='continuation_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='continued_from', to='periodicals.Article'),
        ),
        migrations.AddField(
            model_name='article',
            name='continuation_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='continues_in', to='periodicals.Article'),
        ),
        migrations.AddField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='periodicals.Issue'),
            preserve_default=False,
        ),
    ]
