# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0007_page_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.RemoveField(
            model_name='article',
            name='page',
        ),
    ]
