# Generated by Django 2.0.3 on 2018-03-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0007_rename_field_edition_on_issue_to_edition_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueEdition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
