# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0008_remove_page_from_article_squashed_0017_alter_field_page_on_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='periodicals.Publication'),
        ),
    ]
