# Generated by Django 2.0.3 on 2018-04-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0009_issue_edition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='edition',
        ),
        migrations.DeleteModel(
            name='IssueEdition',
        ),
    ]
