# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0009_article_page_m2m'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='page',
            new_name='pages',
        ),
    ]
