# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0009_issue_related_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_in_issue', to='periodicals.Issue'),
        ),
        migrations.AlterField(
            model_name='article',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles_in_page', to='periodicals.Page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='periodicals.Issue'),
        ),
    ]
