# Generated by Django 2.0.3 on 2018-04-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0010_delete_model_issueedition'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='edition',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
