# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 12:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0011_auto_20171005_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bounding_box',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
        ),
    ]
