# Generated by Django 2.0.3 on 2018-04-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0011_issue_edition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['publication', 'issue_date', 'edition']},
        ),
        migrations.RemoveField(
            model_name='issue',
            name='edition_number',
        ),
    ]
