# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0011_article_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='issue',
        ),
    ]
