# Generated by Django 2.0.3 on 2018-04-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0012_remove_field_edition_number_from_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='abbreviation',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=models.SlugField(max_length=5),
        ),
    ]
