# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0013_remove_article_pages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['page', 'aid']},
        ),
        migrations.AddField(
            model_name='article',
            name='page',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='periodicals.Page'),
            preserve_default=False,
        ),
    ]
