# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-05 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0013_auto_20171005_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='width',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
