# Generated by Django 2.0.3 on 2018-04-05 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0013_alter_fields_on_publication'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publication',
            unique_together={('abbreviation', 'slug', 'title')},
        ),
    ]
