# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0014_article_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='continuation_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='continued_from', to='periodicals.Article'),
        ),
        migrations.AddField(
            model_name='article',
            name='continuation_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='continues_in', to='periodicals.Article'),
        ),
    ]
