# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0014_auto_20171005_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='position_in_page',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
