# Generated by Django 2.0.4 on 2018-04-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0014_alter_unique_together_for_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='total_page_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='year_from',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='year_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
