# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0015_article_position_in_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['page', 'position_in_page', 'aid']},
        ),
        migrations.AlterField(
            model_name='article',
            name='position_in_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
