# Generated by Django 2.0.4 on 2018-04-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0015_optimisation_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='total_page_count',
        ),
        migrations.AddField(
            model_name='publication',
            name='issue_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publication',
            name='page_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
