# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0016_article_position_in_page_blank_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='pdf',
            field=models.FileField(null=True, upload_to='periodicals/'),
        ),
    ]
