# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0016_article_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='periodicals.Page'),
        ),
    ]
