# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0016_article_position_in_page_blank_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
