# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0017_article_title_increase_length'),
        ('periodicals', '0017_issue_pdf'),
    ]

    operations = [
    ]
