# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0017_issue_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
