# Generated by Django 2.0.4 on 2018-04-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0017_optimisation_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='article_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
