# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0018_merge_issue_pdf_article_title_increase_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='slug',
            field=models.SlugField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
