# Generated by Django 2.0.3 on 2018-04-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0018_optimisations_4'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['position_in_page', 'aid']},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['issue_date', 'edition']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['number']},
        ),
    ]
