# Generated by Django 2.0.4 on 2018-06-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    def resave(apps, schema_editor):
        Publication = apps.get_model('periodicals', 'Publication')

        for p in Publication.objects.all():
            p.save()

    dependencies = [
        ('periodicals', '0020_re_save_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='article_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(resave)
    ]
