# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0021_publication_slug_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='slug',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
