# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 13:37
from __future__ import unicode_literals

from django.db import migrations
from django.utils.text import slugify


def set_slug(apps, schema_editor):
    Issue = apps.get_model('periodicals', 'Issue')

    for obj in Issue.objects.all():
        obj.slug = slugify(obj.uid)
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0022_issue_slug'),
    ]

    operations = [
        migrations.RunPython(set_slug, migrations.RunPython.noop)
    ]
