# Generated by Django 2.0.4 on 2018-06-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0022_add_label_to_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_department',
            field=models.BooleanField(default=False),
        ),
    ]
