# Generated by Django 2.0.4 on 2018-11-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0023_department_boolean_on_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='headnotes_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
