# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0024_issue_slug_unique'),
        ('periodicals', '0018_article_content_html'),
    ]

    operations = [
    ]
