# Generated by Django 2.0.4 on 2018-11-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0024_headnotes_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='weekly',
            field=models.BooleanField(default=True),
        ),
    ]
