# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0025_merge_of_0018_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
