# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0026_articletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to='periodicals/'),
        ),
    ]
