# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0030_article_slug_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['page__number', 'position_in_page', 'aid']},
        ),
    ]
