# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0031_article_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='title',
            field=models.CharField(max_length=2048),
        ),
    ]
