# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-04 17:14
from __future__ import unicode_literals

from django.db import migrations, models
from periodicals.models import Publication

''' This just re-saves all publications to generate
the ordering'''
def save_all_publications(apps, schema_editor):
    publications = Publication.objects.all()
    for p in publications:
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0032_increasing_varchar_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='ordering',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
                migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['ordering']},
        ),
        # Reverse does nothing here.
        migrations.RunPython(save_all_publications, save_all_publications),
    ]
