# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicals', '0034_publication_title_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
